version: '3.5'
  
services:
    crawler:
        image: webrecorder/browsertrix-crawler:0.3.0
        build:
          context: ./

        ports:
          - 9037:9037

        volumes:
          - ./crawls:/crawls

        cap_add:
          - NET_ADMIN
          - SYS_ADMIN

        shm_size: 1gb
